# Generated by Django 4.0.4 on 2022-08-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('', ''), ('Breakfast', 'BREAKFAST'), ('hors_devours', "HORS D'OEUVRES"), ('soup', 'SOUP'), ('salad', 'SALAD'), ('beef', 'BEEF'), ('fish', 'FISH'), ('poultry', 'POULTRY')], default='', max_length=16),
        ),
    ]
